networks:
  webapp: {}

volumes:
  sql_data: {}
  avatar_data: {}

services:
  # Nginx with SSL
  nginx:
    build: ./security
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks: [webapp]
    restart: unless-stopped


  # Backend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - HOST_IP=${HOST_IP:-localhost}
    expose:
      - "8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST_IP=${HOST_IP:-localhost}
    networks: [webapp]
    restart: unless-stopped
    
  
  # frontend service
  backend:
    build: ./backend
    env_file:
      - .env
    expose:
      - "3000"
    networks: [webapp]
    volumes:
      - sql_data:/app/data
      - avatar_data:/app/public/avatars
    restart: unless-stopped